# Generated by Django 4.0.5 on 2023-05-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.IntegerField(default=0)),
                ('player2', models.IntegerField(default=0)),
                ('hplayer1', models.IntegerField(default=2000)),
                ('hplayer2', models.IntegerField(default=2000)),
                ('status', models.IntegerField(default=0)),
                ('turn', models.IntegerField(default=1)),
            ],
        ),
    ]
